on:
  pull_request:
    branches-ignore:
    - main
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishUrl: https://dev.semgrep.dev
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 306
